tasks:
  - name: setup-aws
    env:
     AWS_CLI_AUTO_PROMPT=on-partial 
    init: |
      sudo apt-get update && sudo apt-get install -y unzip curl
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      sudo ./aws/install
      aws --version